#!/bin/bash

arm-none-eabi-objcopy -O ihex "${1}" "${1}.hex"

arm-none-eabi-objcopy -O binary "${1}" "${1}.bin"
arm-none-eabi-objdump -C -D "${1}" > "${1}.S"

arm-none-eabi-size "${1}"

mkfw "${1}".bin "${1}".fw

